language: node_js
node_js:
- '8'
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_95e24e700a4c_key -iv $encrypted_95e24e700a4c_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'Ghostdar'
- git config --global user.email 848760247@qq.com
install:
- npm install hexo-cli -g
- npm install
script:
- npm run deploy
cache:
  directories:
  - node_modules